version: '3'

services:
  web:
    build:
      context: ./src
    ports:
      - "8000:8000"
    networks:
      - django_network
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network: