# Generated by Django 4.2.15 on 2024-10-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_dish_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_view_dish", "Может просматривать блюда")],
                "verbose_name_plural": "dishes",
            },
        ),
    ]
