# Generated by Django 4.2.15 on 2024-11-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_specialhours_remove_restaurant_open_from_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workinghours",
            unique_together={("day_of_week", "opening_time", "closing_time")},
        ),
    ]
